services:
  nginx:
    image: nginx:alpine
    depends_on:
      - api
    env_file:
      - .dockerenv
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    command: /bin/sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - "0:8080"
    networks:
      - backend

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "5000"
    networks:
      - backend

networks:
  backend:
